general {
    lock_cmd = noctalia-shell ipc call lockScreen lock              # не плодить несколько экземпляров
    before_sleep_cmd = loginctl lock-session          # блокировка перед suspend
    # after_sleep_cmd = hyprctl dispatch dpms on        # DPMS после пробуждения
    ignore_dbus_inhibit = false                       # игнорировать idle-inhibit по dbus
}

listener { 
    timeout = 180                                                      # 3 минуты
    # Список устройств: brightnessctl --list
    # Подсветка клавиатуры: brightnessctl -d kbd_backlight set 50%
    on-timeout = brightnessctl --save --device=kbd_backlight set 0     # выкл. подсветку клавиатуры
    on-resume = brightnessctl --restore --device=kbd_backlight         # вкл. подсветку клавиатуры
}

listener {
    timeout = 600                                # 10 мин
    on-timeout = brightnessctl -s set 10         # минимум яркости монитора; 0 на OLED не ставить
    on-resume = brightnessctl -r                 # восстановить яркость монитора
}

listener {
    timeout = 1200                                     # 20 минут
    on-timeout = noctalia-shell ipc call lockScreen lock           # блокировка экрана
}

# listener {
#     timeout = 1660                                             # 31 минута
#     on-resume = brightnessctl -r   # монитор и экран вкл.
# }

# listener {
#     timeout = 1800                                # 30 мин
#     on-timeout = systemctl suspend                # suspend ПК
# }
